name: Build and Publish Custom Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare apps.json secret
        run: |
          echo 'APPS_JSON<<EOF' >> $GITHUB_ENV
          cat apps.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/layered/Containerfile
          push: true
          tags: ghcr.io/acmesoftwarellc/frappe-hrms:version-15
          secrets: |
            apps_json=${{ env.APPS_JSON }}
          build-args: |
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-15
